# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger: 
#none
  branches:
    include:
      - main
      - develop
pr: none
#  branches: none
#    include:
#      - main
#      - develop
#      - feature/*
#    exclude:
#      - test/*   #esta propiedad excluye los pr asociados a esta rama

resources:
- repo: self

variables:
- group: test
  


stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
  
#    - task: CmdLine@2
#      inputs:
#        script: echo $(test) 
#    - task: CmdLine@2
#      inputs:
#        script: echo $(test2)       
    
    - task: CmdLine@2
      displayName: git clone
      inputs:
        script: | 
          echo $(Build.SourceBranch)
          ls -lah
          git clone https://github.com/PastranaGit/test-azure.git
          cd test-azure
          ls -lah
          pwd
   
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHubDemo'
        repository: 'pastranahub/pastrana-registry'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourceBranch)/test-azure/Dockerfile'
        
    #

    