# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger: 
#none
  branches:
    include:
      - main
pr: none
#  branches: none
#    include:
#      - main
#      - develop
#      - feature/*
#    exclude:
#      - test/*   #esta propiedad excluye los pr asociados a esta rama

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    
    
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHubDemo'
        repository: 'pastranahub/pastrana-registry'
        command: 'buildAndPush'
        Dockerfile: $(Build.SourcesDirectory)/Dockerfile
    
    